### ISSUE TITLE
Unstake failed: Authorization failure with sent deferred transaction consisting only of actions to self

### ISSUE THREAD

**Issue by flyq** [crypto-meetup-dev/cryptomeetup-contracts#34]
Error message:
> Unstake failed: Authorization failure with sent deferred transaction consisting only of actions to self

from terminal:
> Error 3100006: Subjective exception thrown during block production
Error Details:
Authorization failure with sent deferred transaction consisting only of actions to self
transaction declares authority '{"actor":"tmonomonomon","permission":"active"}', but does not have signatures for it under a provided delay of 60000 ms, provided permissions [{"actor":"cryptomeetup","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
pending console output: 

It executed successfully when 12/6/2018 7:56:58 PM
https://eosflare.io/tx/2f1748c3324568c83c374d16fd4225bfa9f607cc883ab91050f52bd4e0d1b878
https://eosflare.io/tx/ccd977689a1f32aa9c64f689da8a02244161d657c47f9d5ca248793b8dbd562c

and the code of the contract is the same.

According to:
https://github.com/EOSIO/eos/blob/master/libraries/chain/apply_context.cpp#L347

**Comment by flyq** [comment]
EOS updated to 1.5.1, and changed the authorization code
https://github.com/EOSIO/eos/commit/8f1de5c6e370a270e7dd38bce22ab122ef4ce8a3

**Comment by lychees** [comment]
I changed the permission from user to contract self, and it seems that evverything is OK now.
<img width="1248" alt="2018-12-19 11 26 12" src="https://user-images.githubusercontent.com/2507027/50234030-b6c5e380-03ef-11e9-8a55-cdcfd7b60f3e.png">

https://github.com/crypto-meetup-dev/cryptomeetup-contracts/commit/dac3bfb3e994c99f81522ef635b19a7f11376312
